version: "{build}"
clone_depth: 5
build: off

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%\bin;%PATH%
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle

environment:
  matrix:
    - RUBY_FOLDER_VER: "25"
    - RUBY_FOLDER_VER: "25-x64"
    - RUBY_FOLDER_VER: "24"

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash script/cibuild

cache:
  - 'vendor\bundle -> appveyor.yml,Gemfile,jekyll-commonmark.gemspec'
