name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: "Unit Tests w/ Jekyll {{ matrix.jekyll_version }} (Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.6
          - 2.7
          - 3.0
        jekyll_version:
          - "~> 4.2"
        include:
          ruby_version: 2.6
          jekyll_version: "~> 3.9"
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll_version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Execute tests
        run:  bundle exec rspec

  style_check:
    name: "Style Check (Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.6
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run RuboCop
        run:  bash script/fmt
